version: 2.1

jobs:
  deploy-rollback:
    docker:
      - image: cimg/base:stable
    environment:
      COMPONENT_NAME: "<< pipeline.deploy.component_name >>"
      ENVIRONMENT_NAME: "<< pipeline.deploy.environment_name >>"
      NAMESPACE: "<< pipeline.deploy.namespace >>"
      TARGET_VERSION: "<< pipeline.deploy.target_version >>"
    steps:
      - checkout
      - run:
          name: Plan rollback
          command: |-
            circleci run release plan deploy-rollback \
              --environment-name=${ENVIRONMENT_NAME} \
              --component-name=${COMPONENT_NAME} \
              --target-version=${TARGET_VERSION} \
              --rollback
      - run:
          name: Perform rollback
          command: |
            # TODO: add rollback logic using ${TARGET_VERSION}
      - run:
          name: Update deployment status to failed
          command: circleci run release update deploy-rollback --status=FAILED
          when: on_fail
  cancel-deploy-rollback:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Update planned release to CANCELED
          command: |
            circleci run release update deploy-rollback \
              --status=CANCELED
  deploy-rollback-release:
    type: release
    plan_name: deploy-rollback
    validation:
      enabled: true


workflows:
  rollback:
    jobs:
      - deploy-rollback
      - deploy-rollback-release:
          requires:
            - deploy-rollback
      - cancel-deploy-rollback:
          requires:
            - deploy-rollback:
              - canceled